### ISSUE TITLE
OptionValue::nodef: Unknown option MetaInformation for TemplateObject.

### ISSUE THREAD

**Issue by nickknyc** [WolframResearch/Chatbook#156]
Windows 11, Mathematica 13.2

I get this on every interaction.. Using any of the templates - or just "need" it in a default one

**Stack Trace for General::Stop**

Message[General::stop, OptionValue::nodef]
Message[OptionValue::nodef, "MetaInformation", TemplateObject]
OptionValue[TemplateObject, {CombinerFunction -> StringJoin, 
  InsertionFunction -> TextString, 
  MetaInformation -> <||>}, InsertionFunction]

Quiet[Needs["Wolfram`Chatbook`" -> None]]; 
Symbol["Wolfram`Chatbook`ChatbookAction"]["EvaluateChatInput", \
CellObject[
 ChatInput]]

  **StackTrace for OptionValue::nodef**
  
  Message[OptionValue::nodef, "MetaInformation", TemplateObject]
  OptionValue[TemplateObject, {CombinerFunction -> StringJoin, 
  InsertionFunction -> TextString, 
  MetaInformation -> <||>}, InsertionFunction]
  Quiet[Needs["Wolfram`Chatbook`" -> None]]; 
Symbol["Wolfram`Chatbook`ChatbookAction"]["EvaluateChatInput", \
CellObject[
 ChatInput]]

**Comment by rhennigan** [comment]
Can you try evaluating the following and see if that resolves the issue?
```
PacletInstall["Templating" -> "1.50", UpdatePacletSites -> True]
```

**Comment by nickknyc** [comment]
The upgrade did not go smoothly - had to manually uninstall - that was not smooth either. Noticed that paclets were getting stored in 2 different locations. So I am uninstalling everything (wolfram product on my machine) and then reinstalling. Will report back.

**Comment by nickknyc** [comment]
Clean install of Mathematica - no issues - closing issue
