### ISSUE TITLE
trying to click "install from URL"

### ISSUE THREAD

**Issue by warmersun** [WolframResearch/Chatbook#185]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.29"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Microsoft Windows (64-bit) (January 31, 2023)"`` |
| KernelVersion | ``"13.2.1 for Microsoft Windows (64-bit) (January 27, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`PersonaURLInstall[$Failed]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
This is a direct result of issue #187.
