### ISSUE TITLE
`EvaluationCell[]` can sometimes return bad values due to preemptive dynamic evaluations elsewhere

### ISSUE THREAD

**Issue by rhennigan** [WolframResearch/Chatbook#187]
`EvaluationCell[]` can sometimes return the incorrect cell due to preemptive dynamic evaluations elsewhere. This results in all sort of chat notebook functionality breaking.

We need a robust workaround.

**Comment by jfultz** [comment]
I think this is fixed in 13.3.  But the typical way of dealing with this would be to memoize the CellObject into the interface (as, say, a DynamicModule variable).

**Comment by warmersun** [comment]
it seems to me that Wolfram R&D engineers are testing in 13.3 - as per @jfultz 
whereas early adopters like myself are still running on 13.2

Is there a workaround?

**Comment by warmersun** [comment]
lol, I've just seen the blog post from Stephen Wolfram saying 13.3 is out... I'll try with that. Thanks!
