### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by Matariki** [WolframResearch/Chatbook#188]
When switching from gpt-3.5 to gpt-4 I get an error on Mac from ChatbookAction: The model: `gpt-4` does not exist

"ChatbookAction::UnknownStatusCode" with the Message: 	Unexpected response from OpenAI server with status code 404

![Screenshot 2023-06-20 at 16 33 09](https://github.com/WolframResearch/Chatbook/assets/4358599/988e109c-e6be-4843-a4d1-67f2077403ae)

**Comment by rhennigan** [comment]
This is the error message that OpenAI returns if you don't have access to the specified model. They unfortunately use the same error message for both of these cases:

<img width="812" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/6674723/00f65a1b-92a1-4b5b-863c-f7fbe7fb9bea">

* `gpt-4-32k` exists, but I don't have access with my API key
* `hal-9000` doesn't exist

[See here](https://platform.openai.com/docs/models/gpt-4) for more details.

**Comment by Matariki** [comment]
This explains it. I have access to GPT-4-8k but not 32k. Could that be made more clear in the menu where the item reads gpt-4-32k? Or better be added to the menu so you can choose 8k or 32k?

**Comment by raverydavis** [comment]
Just to be clear, the menu entry is for gpt-4 model, not gpt-4-32k. It would make sense to add gpt-4-32k as an option in the menu but as far as I know that model is still very limited. I might argue it makes sense to add the 32k model when it's more widely available to prevent confusion :)
