### ISSUE TITLE
Errors can sometimes be returned from the API with a 200 status code

### ISSUE THREAD

**Issue by warmersun** [WolframResearch/Chatbook#193]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.30"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Microsoft Windows (64-bit) (January 31, 2023)"`` |
| KernelVersion | ``"13.2.1 for Microsoft Windows (64-bit) (January 27, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeReformattedCell[<|"Assistance" -> Automatic, "AutoFormat" -> True, "BasePrompt" -> Automatic, "ChatContextCellProcessingFunction" -> Automatic, "ChatContextPostEvaluationFunction" -> Automatic, "ChatContextPreprompt" -> Automatic, "ChatDrivenNotebook" -> False, "ChatHistoryLength" -> 25, "DynamicAutoFormat" -> Automatic, "FrequencyPenalty" -> 0.1, "IncludeHistory" -> Automatic, "LLMEvaluator" -> <|"Pre" -> "You are a helpful Wolfram Language assistant named ...
  "Arguments" -> {}
|>
```

</details>

**Comment by raverydavis** [comment]
Hi! Thanks for the report. Any description of what you did to trigger the error?

**Comment by warmersun** [comment]
Wasn't really doing anything when it popped up.
Otherwise I'm working on a function that interprets HistoricalCountry -
instead of the built in Interpreter I try to use LLMFunction.

I get a warning that says one definition of LLMFunction overshadows the
other.
I don't understand why...
It's now defined at the system level, no need for using `Needs[...]`

**Comment by rhennigan** [comment]
I was able to replicate the same type of failure. I tracked it down to the OpenAI API returning an error, but still giving a 200 status code.
