### ISSUE TITLE
Internal error when "BodyChunkRecieved" data is incomplete

### ISSUE THREAD

**Issue by stoney** [WolframResearch/Chatbook#210]
The streaming data from the API may not always contain a complete data line, which will lead to internal errors. These should be buffered and joined as needed.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.30"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Mac OS X ARM (64-bit) (June 3, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeChunk[Dynamic[Wolfram`Chatbook`Actions`Private`container$49890], CellObject["4d2edfd5-f873-4cb0-985f-946480a786a6", "d0cad54a-4395-4654-a134-01c7c9dd618a"], "\"finish_reason\":null}]}\n\n"]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
Updated title and description to reflect the underlying issue.
