### ISSUE TITLE
[CASE:5056599] Debug Data

### ISSUE THREAD

**Issue by notfortraining** [WolframResearch/Chatbook#211]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"0.0.27"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Linux x86 (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Linux x86 (64-bit) (June 3, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| LLMEvaluator | ``"CodeWriter"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeReformattedCell[<|"Assistance" -> Automatic, "AutoFormat" -> True, "BasePrompt" -> Automatic, "ChatContextCellProcessingFunction" -> Automatic, "ChatContextPostEvaluationFunction" -> Automatic, "ChatContextPreprompt" -> Automatic, "ChatDrivenNotebook" -> False, "ChatHistoryLength" -> 25, "DynamicAutoFormat" -> Automatic, "FrequencyPenalty" -> 0.1, "IncludeHistory" -> Automatic, "LLMEvaluator" -> <|"Pre" -> "As a helpful Wolfram Language code writer, your job...
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
Closing due to insufficient actionable information
