### ISSUE TITLE
How can a sandboxed Wolfram Language evaluator be used by default?

### ISSUE THREAD

**Issue by gwr69** [WolframResearch/Chatbook#220]
Having read Stephen Wolfram's [release blog](https://writings.stephenwolfram.com/2023/06/llm-tech-and-a-lot-more-version-13-3-of-wolfram-language-and-mathematica/) for `v13.3` I was intrigued to see that one now obviously can have the same experience as someone working in OpenAI's web interface with the Wolfram PlugIn:

[![Wolfram Blog][1]][1]

Unfortunately, using a **Chat-Enabled Notebook** in `v13.3` does not give the same result:

[![Replication][2]][2]

**How can a "sandboxed" Wolfram Language Evaluator be employed in the way it was done for the release blog?**

Note: I crossposted this issue on Mathematica Stack Exchange ([287083](https://mathematica.stackexchange.com/q/287083/764)).
  
[1]: https://i.stack.imgur.com/DgTIQ.png
[2]: https://i.stack.imgur.com/TiNJN.png

**Comment by rhennigan** [comment]
The tools are currently only enabled by default for GPT-4, since GPT-3.5 almost always fails to use them correctly. If you have access to GPT-4 with your API key, you should be able to see outputs like these when using that model. Note that for that particular example, GPT-4 makes a call to the WL evaluator approximately 60% of the time, so it's not guaranteed that you'll see similar results.

If you want to force GPT-3.5 to use tools, you can enable it via the "ToolsEnabled" option when creating the notebook:
```
CreateNotebook["ChatEnabled", "ToolsEnabled" -> True]
```
However, GPT-3.5 simply does not understand the tool-calling instructions, so you will not get useful results.

**Comment by orospakr** [comment]
Hey @rhennigan 

I have the same issue. Wolfram Desktop 13.3.1.0.

However, I have confirmed that my OpenAI API key has GPT-4 access by using: `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`, and seeing the GPT-4 models listed. However, asking the LLM ChatInput in a Chat-Enabled Notebook always yields a code snippet and no use of the Evaluator, even after repeated tries in multiple sessions.

I've even tried using `CreateNotebook["ChatEnabled", "ToolsEnabled" -> True]`, but that appeared to have no effect.

I've tried to prompt the Assistant to reveal which GPT model it is based on, but it swears it is a Assistant developed by Wolfram Research and in no way related to the GPT models from OpenAI. Har har :)

**Comment by orospakr** [comment]
Hmm, perhaps a permission is missing?

```
{
      "id": "gpt-4",
      "object": "model",
      "created": 1687882411,
      "owned_by": "openai",
      "permission": [
        {
          "id": "modelperm-cOSx57rPrEzolEUD2QSSACPS",
          "object": "model_permission",
          "created": 1692411452,
          "allow_create_engine": false,
          "allow_sampling": false,
          "allow_logprobs": false,
          "allow_search_indices": false,
          "allow_view": false,
          "allow_fine_tuning": false,
          "organization": "*",
          "group": null,
          "is_blocking": false
        }
      ],
      "root": "gpt-4",
      "parent": null
    }
```

**Comment by raverydavis** [comment]
> Hey @rhennigan
> 
> I have the same issue. Wolfram Desktop 13.3.1.0.
> 
> However, I have confirmed that my OpenAI API key has GPT-4 access by using: `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`, and seeing the GPT-4 models listed (namely `gpt-4`, `gpt-4-0613`, and `gpt-0314`). However, asking the LLM ChatInput in a Chat-Enabled Notebook always yields a code snippet and no use of the Evaluator, even after repeated tries in multiple sessions. I've just been trying simple prompts like asking it to plot sin(x).
> 
> I've even tried using `CreateNotebook["ChatEnabled", "ToolsEnabled" -> True]`, but that appeared to have no effect.
> 
> I've tried to prompt the Assistant to reveal which GPT model it is based on, but it swears it is a Assistant developed by Wolfram Research and in no way related to the GPT models from OpenAI. Har har :)

`CreateNotebook["ChatEnabled", "Model" -> "gpt-4"]` Open a new Chat Notebook with gpt-4 as the selected model

**Comment by orospakr** [comment]
Aha, that's done it. Thanks @rhennigan .

I presume this will be fixed in a future Wolfram release?

**Comment by orospakr** [comment]
@rhennigan ah I'm afraid there's another issue: the evaluator seems to display no results, regardless of the request.

Should I open another GitHub ticket for this issue, or should I file it somewhere else?

<img width="780" alt="CleanShot 2023-08-21 at 14 49 45@2x" src="https://github.com/WolframResearch/Chatbook/assets/16714/7801ece8-de78-4273-a8d4-aff15c54ace7">

**Comment by raverydavis** [comment]
@orospakr Does it happen every time or was this a one-off instance? It's possible the LLM didn't format the text correctly to invoke a tool call

**Comment by Razboy20** [comment]
I am also having the same problem: This error is displayed alongside the above result shown by @orospakr in messages: 
![image](https://github.com/WolframResearch/Chatbook/assets/29903962/8166dd8f-33c8-4576-b6bb-5289f06b563f)

**Comment by raverydavis** [comment]
> I am also having the same problem: This error is displayed alongside the above result shown by @orospakr in messages: ![image](https://user-images.githubusercontent.com/29903962/269093237-8166dd8f-33c8-4576-b6bb-5289f06b563f.jpeg)

This bug should be fixed with recent versions of the LLMFunctions and Chatbook paclet in version 13.3. Running
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
PacletInstall["Wolfram/LLMFunctions", UpdatePacletSites -> True]
```
should fix that - if not please let us know what Wolfram version you're using and what version those paclets return

**Comment by Razboy20** [comment]
> > I am also having the same problem: This error is displayed alongside the above result shown by @orospakr in messages: ![image](https://user-images.githubusercontent.com/29903962/269093237-8166dd8f-33c8-4576-b6bb-5289f06b563f.jpeg)
> 
> This bug should be fixed with recent versions of the LLMFunctions and Chatbook paclet in version 13.3. Running
> 
> ```
> PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
> PacletInstall["Wolfram/LLMFunctions", UpdatePacletSites -> True]
> ```
> 
> should fix that - if not please let us know what Wolfram version you're using and what version those paclets return

Ah perfect, thank you! That does solve the problem.
