### ISSUE TITLE
Chat icon not appearing in toolbar

### ISSUE THREAD

**Issue by wbpayne22902** [WolframResearch/Chatbook#223]
I have Mathematica 13.3 installed on two computers with this paclet installed.  On one of these computers, in the toolbar in my notebooks there is an chat-bubble icon that I can click to change the persona for the entire notebook.  I do not have this toolbar icon on my second computer and am wondering whether this is a bug or if I'm not doing something right.

**Comment by rhennigan** [comment]
The paclet manager only checks for updates occasionally, so you likely just haven't gotten the updated toolbar paclet yet. Try `PacletInstall["NotebookToolbar", UpdatePacletSites -> True]` to force the update then restart Mathematica.

**Comment by wbpayne22902** [comment]
You were absolutely correct @rhennigan.  The updated toolbar paclet did fix it.  It's good to know I would have gotten the icon eventually even if I had not used the command you suggested.  Thanks!
