### ISSUE TITLE
Symbols leak into global context?

### ISSUE THREAD

**Issue by yuriever** [WolframResearch/Chatbook#291]
Hi! When using this paclet with version 1.0.4 I find there are lots of symbols appearing in global context. Some of them are locked and protected, and I'm not sure whether this may cause unwanted behaviour when ``Quiet@ClearAll["`*"]``.

My version is 
<img width="813" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/104705457/199ef271-ac67-439a-a3de-7a423a044613">

## At startup 
<img width="804" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/104705457/2aefc8f3-538e-4ee4-8ebc-ccd83c828746">

The first symbol `next` is mentioned in https://github.com/WolframResearch/Chatbook/issues/289. I have no idea about the second `res`.

## Open the chatbook

<img width="801" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/104705457/bed69729-1ba0-4e54-bb36-622cfc44a1bd">

Some of them are option names.

## Create a dialog

<img width="813" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/104705457/2590d503-38d9-4786-bee9-fc7b1469d32f">

<img width="799" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/104705457/6e23b73f-e321-4b8b-8741-1340cf659c5b">

---

Do the symbols appearing after opening chatbook and creating dialog come from this paclet? If so, will this be fixed?

**Comment by rhennigan** [comment]
Many of those appear to be Notebook options, which unfortunately do get created in Global:
```
In[1]:= Names["`*"] // Length

Out[1]= 0

In[2]:= Options @ Notebook;

In[3]:= Names["`*"] // Length

Out[3]= 17
```

I'm not sure about the rest of those symbols. I'm not seeing those in my session after using chat notebooks.
