### ISSUE TITLE
1

### ISSUE THREAD

**Issue by josesamaca** [WolframResearch/Chatbook#309]
Cuál es el código para crear un gráfico de una función en wólfram

**Comment by rhennigan** [comment]
(Answer and translation by GPT-4)

Para crear un gráfico de una función en el Lenguaje Wolfram, puedes usar la función [Plot](https://reference.wolfram.com/language/ref/Plot.html). Aquí hay un ejemplo en el que trazamos la función $y = x^2$: 
```Wolfram
Plot[x ^ 2, {x, -10, 10}]
```
Aquí ``x ^ 2`` es la función que queremos trazar y ``{x, -10, 10}`` especifica el rango del eje x, desde -10 hasta 10. 

Si quieres etiquetar los ejes para que el gráfico sea más claro, puedes agregar una opción [AxesLabel](http://reference.wolfram.com/language/ref/AxesLabel.html): 
```Wolfram
Plot[x ^ 2, {x, -10, 10}, AxesLabel -> {"x", "y"}]
```
Esto colocará la etiqueta "x" en el eje x y la etiqueta "y" en el eje y.
