### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by spasetto** [WolframResearch/Chatbook#320]
It does not work.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.1.1"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Microsoft Windows (64-bit) (November 18, 2022)"`` |
| KernelVersion | ``"13.2.0 for Microsoft Windows (64-bit) (November 18, 2022)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |

## Stack Data
```
catchTop
checkResponse
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`toolFreeQ[ProgressIndicator[Appearance -> "Percolate"]]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
Duplicate of #296
