### ISSUE TITLE
GPT 4 wont work

### ISSUE THREAD

**Issue by CColeMcK** [WolframResearch/Chatbook#328]
| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.1.1"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Mac OS X ARM (64-bit) (June 3, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| LLMEvaluator | ``"PlainChat"`` |
| ChatNotebookSettings | ``<|"LLMEvaluator" -> "PlainChat"|>`` |

## Stack Data
```
catchTop
checkResponse
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`toolFreeQ[ProgressIndicator[Appearance -> "Percolate"]]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
Fixed in #297
