### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by nadluru** [WolframResearch/Chatbook#337]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.4"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X x86 (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Mac OS X x86 (64-bit) (July 24, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
catchTop
checkResponse
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`toolFreeQ[ProgressIndicator[Appearance -> "Percolate"]]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
Fixed in #297
