### ISSUE TITLE
Output of the web search tool mentions the web fetch tool, which may not be enabled

### ISSUE THREAD

**Issue by raverydavis** [WolframResearch/Chatbook#378]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

This is what I entered "Summarize https://en.wikipedia.org/wiki/2024_Summer_Olympics" using GPT-4 and enabling web searching for Code Assistant.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.1.3"`` |
| ReleaseID | ``"a8a1901400c0585e63aa32a1ef01fad45bfeab56"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (June 8, 2023)"`` |
| KernelVersion | ``"13.3.0 for Mac OS X ARM (64-bit) (June 8, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.1.3.3903517535"`` |

## Stack Data
```
joinAdjacentStrings
inlineToolCall
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Formatting`Private`parseFullToolCallString["48a047757ab52f77", Failure["InvalidLLMToolRequestName", <|"MessageTemplate" -> "No tool with name `1` found from tool list.", "MessageParameters" -> {"web_fetcher"}, "CallName" -> "web_fetcher", "LLMTools" -> {LLMTool[<|"CanonicalName" -> "DocumentationLookup", "DisplayName" -> "Documentation Lookup", "Name" -> "documentation_lookup", "Icon" -> RawBoxes[TemplateBox[{}, "ToolIconDocumentationLookup"]], "Description" -> "Get documentatio...
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$109543
|>
```

</details>

**Comment by rhennigan** [comment]
I found the issue here: https://github.com/WolframResearch/Chatbook/blob/3d6c5da1ca7a71f4bf5f2581beb58f4290bce73d/Source/Chatbook/Tools.wl#L1076-L1078

The output of the web search tool mentions the web fetch tool, which isn't guaranteed to be available. This should be a straightforward fix.
