### ISSUE TITLE
Error asking LLM to format evaluation with commas

### ISSUE THREAD

**Issue by raverydavis** [WolframResearch/Chatbook#382]
Using claude-2, I asked it to give me a prime number (111,111th prime). It successfully gave me the number. Next, I asked it to format that number. It errored with this

<img width="734" alt="image" src="https://github.com/WolframResearch/Chatbook/assets/10748455/fcd36af6-8799-408d-b422-fae4cd555acc">

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.2.1"`` |
| ReleaseID | ``"$RELEASE_ID$"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X ARM (64-bit) (October 2, 2023)"`` |
| KernelVersion | ``"14.0.0 Prototype version for Mac OS X ARM (64-bit) (October 2, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| ToolSelections | ``<\|"WolframAlpha" -> <\|"TestPromptPersona" -> True\|>, "WebFetcher" -> <\|"PlainChat" -> False\|>, "WebImageSearcher" -> <\|"PlainChat" -> False\|>\|>`` |
| ToolSelectionType | ``<\|\|>`` |
| Model | ``{"Anthropic", "claude-2"}`` |
| DocuToolsSettingsInternal | ``<\|"$ApplicationName" -> "Pubs", "$LinkBase" -> "Pubs", "$ApplicationDirectory" -> "/Users/averyd/workspace/wolfram/cvs/Pubs/", "$DocumentationDirectory" -> "/Users/averyd/workspace/wolfram/cvs/Pubs/Documentation/English/", "$UseNewPageDialog" -> "", "CloseOpenPageDialogAutomatically" -> True\|>`` |
| ChatNotebookSettings | ``<\|"InheritanceTest" -> True, "ToolSelections" -> <\|"WolframAlpha" -> <\|"TestPromptPersona" -> True\|>, "WebFetcher" -> <\|"PlainChat" -> False\|>, "WebImageSearcher" -> <\|"PlainChat" -> False\|>\|>, "ToolSelectionType" -> <\|\|>, "Model" -> {"Anthropic", "claude-2"}\|>`` |

## Stack Data
```
catchTop
joinAdjacentStrings
inlineToolCall
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Formatting`Private`parseFullToolCallString["5694e5e17d7a8cd5", Failure["InvalidLLMToolRequestName", <|"MessageTemplate" -> "No tool with name `1` found from tool list.", "MessageParameters" -> {"wolfram_language_evaluator "}, "CallName" -> "wolfram_language_evaluator ", "LLMTools" -> {LLMTool[<|"CanonicalName" -> "DocumentationLookup", "DisplayName" -> "Documentation Lookup", "Name" -> "documentation_lookup", "Icon" -> RawBoxes[TemplateBox[{}, "ToolIconDocumentationLookup"]], "D...
  "Argum
```

</details>

**Comment by rhennigan** [comment]
This is an issue with claude-2 adding extra spaces after tool names:
```
<|"MessageTemplate" -> "No tool with name `1` found from tool list.", "MessageParameters" -> {"wolfram_language_evaluator "},
```
There's already a PR in LLMFunctions to address this.
