### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by lee170** [WolframResearch/Chatbook#402]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.4"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeChunk[Dynamic[Wolfram`Chatbook`Actions`Private`container$53342], CellObject["b5f9f2b2-bc22-4695-ab5d-0591b0e8b8e8", "b23d497a-eb9f-4576-92b3-0858ddc57ee8"], ":\"gpt-3.5-turbo-0613\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\" \"},\"finish_reason\":null}]}\n\ndata: {\"id\":\"chatcmpl-89ePltTwAGNv5ln9mxWiBYe95kgEo\",\"object\":\"chat.completion.chunk\",\"created\":1697310997,\"model\":\"gpt-3.5-turbo-0613\",\"choices\":[{\"index\":0,\"delta\":{\"conten...
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
This was fixed in #342. Evaluate `PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]` to get the latest updates.
