### ISSUE TITLE
An unexpected response from server with status code 404 Chatbook::UnknownStatusCode 

### ISSUE THREAD

**Issue by angelkyt** [WolframResearch/Chatbook#420]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.2.2"`` |
| ReleaseID | ``"$RELEASE_ID$"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X x86 (64-bit) (October 16, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X x86 (64-bit) (October 16, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.2.1.3905399249"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`CopyChatObject[CellObject["cc8f526d-1976-4456-9a11-363470a89b4e", "e89524dc-2d76-4440-9818-d460dfcef705"]]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "EncodedString", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {StringQ, Inherited}, "ConfirmationType" -> "ConfirmBy", "Expression" :> Inherited, "Function" :> StringQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$45048
|>
```

</details>

**Comment by rhennigan** [comment]
Fixed in #578
