### ISSUE TITLE
Failure after tool result

### ISSUE THREAD

**Issue by bobohilario** [WolframResearch/Chatbook#431]
Here is the notebook:

https://www.wolframcloud.com/obj/bobs/SharedNBs/chat-error.nb

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.3.0"`` |
| ReleaseID | ``"e00b6cf8cf704b8be1a076ef98717a70deab7304"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X x86 (64-bit) (October 27, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X x86 (64-bit) (October 27, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.3.0.3907219780"`` |

## Stack Data
```
joinAdjacentStrings
openerView
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Formatting`Private`makeToolCallRawView[<|"ID" -> id, "Name" -> "WolframLanguageEvaluator", "DisplayName" -> "Wolfram Language Evaluator", "Icon" -> RawBoxes[TemplateBox[{}, "AssistantEvaluate"]], "ToolCall" -> StringTrim[string], "Parameters" -> parameters, "Result" -> output, "FormattingFunction" -> Wolfram`Chatbook`Sandbox`sandboxFormatter|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$37088
|>
```

</details>

**Comment by rhennigan** [comment]
@bobohilario are you still able to reproduce this, or was this one from when you were testing local changes? Just wanted to confirm before closing.
