### ISSUE TITLE
Using Wolfram Language Evaluator tool fails

### ISSUE THREAD

**Issue by rohitn** [WolframResearch/Chatbook#442]
Trying to use the Wolfram Language Evaluator tool always fails. Tried quitting Mathematica, killing all kernels, same error.

<img width="783" alt="Screenshot 2023-11-03 at 14 42 14" src="https://github.com/WolframResearch/Chatbook/assets/25102/325d4b4e-c44c-411e-93e0-fec0336a6d83">

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.3.0"`` |
| ReleaseID | ``"e00b6cf8cf704b8be1a076ef98717a70deab7304"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Mac OS X ARM (64-bit) (July 24, 2023)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.3.0.3907219780"`` |

## Stack Data
```
catchTopAs
makeHTTPRequest
constructMessages
cellToString
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Serialization`Private`truncateString[$Failed, 5000]
  "Failure" -> Failure[Wolfram`Chatbook`ErrorUtils`DownValueFallthroughError, <|"Symbol" -> Wolfram`Chatbook`Serialization`Private`truncateString, "ArgumentList" -> HoldComplete[{$Failed, 5000}], "MessageTemplate" -> "Arguments applied to symbol `` did not match any DownValues.", "MessageParameters" -> {HoldForm[Wolfram`Chatbook`Serialization`Private`truncateString]}|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$15334
|>
```

</details>

**Comment by rohitn** [comment]
I also tried the following, same error

```LLMSynthesize["What's the 123456789th prime?", 
 LLMEvaluator -> <|"Tools" -> LLMResourceTool["WolframLanguageEvaluator"], "Model" -> "gpt-4"|>]

**Comment by raverydavis** [comment]
1 thing to try, evaluate 1+1 in a new session before creating a new Chat Notebook. The error has to do with timing out from long startup times

**Comment by rhennigan** [comment]
You could also try increasing the timeout duration:
```
Wolfram`Chatbook`SetToolOptions[ "WolframLanguageEvaluator", "EvaluationTimeConstraint" -> 120, "PingTimeConstraint" -> 120 ]
```

Another thing to try is to go to the documentation page for LinkRead and see if those examples work for you. It might be an issue with starting another kernel.

**Comment by rohitn** [comment]
I am unable to reproduce the issue today. The only change I can think of that might have fixed the issue is that I restarted VSCode. I use the WL plugin which starts a kernel. Thanks for your prompt responses.

**Comment by rhennigan** [comment]
> The only change I can think of that might have fixed the issue is that I restarted VSCode. I use the WL plugin which starts a kernel.

That sounds like it could have been hitting license limits for number of running kernels. It would be nice if we had a way to detect this and issue a helpful error message, but I'm not sure if there's a straightforward way of doing that in top-level WL. I'll look into it to see if I can make some improvements there.

If you do run into this issue again, count how many kernels you have running in the activity monitor and compare that against `SystemInformation["Kernel", "MaxLicenseProcesses"]`. If the number of running kernels is lower than that number, there's probably something else going on, in which case, reopen this ticket.
