### ISSUE TITLE
Rate Limit Reached in Chat-Driven Notebook

### ISSUE THREAD

**Issue by prabhchintan** [WolframResearch/Chatbook#443]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.2.0"`` |
| ReleaseID | ``"89cdb48b1ac8ce3a3808948629e7cb8f6673cd9c"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.2 for Mac OS X x86 (64-bit) (January 30, 2023)"`` |
| KernelVersion | ``"13.2.1 for Mac OS X x86 (64-bit) (January 27, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| ChatDrivenNotebook | ``True`` |
| LLMEvaluator | ``"PlainChat"`` |
| Assistance | ``True`` |
| Model | ``"gpt-3.5-turbo-instruct"`` |
| StyleSheetVersion | ``"1.1.3.3903517535"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`CopyChatObject[CellObject["0e8a9e73-667b-45b8-bdb1-8340534b2b9d", "e1837883-82ca-4683-8032-bf21940803ff"]]
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "EncodedString", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {StringQ, Inherited}, "ConfirmationType" -> "ConfirmBy", "Expression" :> Inherited, "Function" :> StringQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$9161
|>
```

</details>

**Comment by rhennigan** [comment]
Fixed in #578
