### ISSUE TITLE
Broken chat not working

### ISSUE THREAD

**Issue by wandwan** [WolframResearch/Chatbook#459]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.2.1"`` |
| ReleaseID | ``"1a6248d091b9dbb893ef68b6db08065925ac6e77"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Cloud: 1.67.0.1 (October 23, 2023)"`` |
| KernelVersion | ``"13.3.1 for Linux x86 (64-bit) (July 24, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |

## Stack Data
```
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`SendChat`Private`prepareChatOutputPage[CellObject["c09d78c1-aac6-4bd7-94df-697e49cd0099", "d8d980d488e54c10a8c35df53d6aeb9f"], Cell[BoxData[DynamicBox[ToBoxes[Refresh[Wolfram`Chatbook`SendChat`Private`x$194725++; If[MatchQ[Wolfram`Chatbook`Formatting`$reformattedCell, _Cell], Pause[1]; NotebookWrite[Wolfram`Chatbook`SendChat`Private`cellObject$193926, Wolfram`Chatbook`Formatting`$reformattedCell]; Remove[Wolfram`Chatbook`SendChat`Private`x$194725, Wolfram`Chatbook`SendChat`Priva...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "NotebookRead", "MessageTemplate" -> "`` does not match ``.", "MessageParameters" :> {$Failed, _Cell}, "ConfirmationType" -> "ConfirmMatch", "Expression" :> $Failed, "Pattern" :> _Cell|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$194727
|>
```

</details>

**Comment by rhennigan** [comment]
Fixed in #574
