### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by wesen** [WolframResearch/Chatbook#461]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.0"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Linux x86 (64-bit) (June 3, 2023)"`` |
| KernelVersion | ``"13.3.0 for Linux x86 (64-bit) (June 3, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

```
Inherited
```

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`writeChunk[Dynamic[Wolfram`Chatbook`Actions`Private`container$8886], CellObject["879f1fc7-847b-4bc0-a2c7-c79001266832", "aa6292dc-faa4-47bc-a1c0-b8b295e3249d"], "\"gpt-3.5-turbo-0613\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"2\"},\"finish_reason\":null}]}\n\ndata: {\"id\":\"chatcmpl-8NlqXlNIt9xpNbP3Go3ShpxYjvruA\",\"object\":\"chat.completion.chunk\",\"created\":1700676157,\"model\":\"gpt-3.5-turbo-0613\",\"choices\":[{\"index\":0,\"delta\":{\"content\...
  "Arguments" -> {}
|>
```

</details>

**Comment by raverydavis** [comment]
@wesen Can you update to a more recent package and see if your issue persists?
You can run `PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]` to get the latest version of the paclet

**Comment by wesen** [comment]
That seems to help, thanks @raverydavis
