### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by justinpearson** [WolframResearch/Chatbook#496]
Hi! Steps to reproduce:
1. new notebook
2. click "speech bubble" in upper right ("Chat notebook settings")
3. click "Code Assistant" persona
4. use single-quote to create new chat-enabled notebook cell
5. type "which version of GPT is this?"
6. see error message

Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.0.4"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 for Mac OS X x86 (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Mac OS X x86 (64-bit) (July 24, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| Assistance | ``True`` |

## Stack Data
```
catchTop
checkResponse
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`Private`toolFreeQ[ProgressIndicator[Appearance -> "Percolate"]]
  "Arguments" -> {}
|>
```

</details>

**Comment by rhennigan** [comment]
This was fixed in #379.

Evaluate the following to get the latest updates:
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
```
