### ISSUE TITLE
Hi Rick

### ISSUE THREAD

**Issue by bobohilario** [WolframResearch/Chatbook#550]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X x86 (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X x86 (64-bit) (December 13, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| Model | ``"gpt-4"`` |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
withBasePromptBuilder
catchTopAs
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`ChatHistory`chatExcludedQ[Inherited]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$488850
|>
```

</details>

**Comment by rhennigan** [comment]
This was due to a bad mouseover event for a chat input cell, which I fixed recently in #536.
