### ISSUE TITLE
Opening Mathematica Preferences generates an error message for the Model information

### ISSUE THREAD

**Issue by oliverjandette** [WolframResearch/Chatbook#596]
I simply opened the AI settings from the Preferences window and an error message was prompted (attached screenshot). I have recently performed a cleanstart and my Chatnotebooks were working as expected afterwards. Now, evaluation of a prompt can make the frontend hang. Eventually I have to kill the process. 

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Microsoft Windows (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Microsoft Windows (64-bit) (December 13, 2023)"`` |
| SystemID | ``"Windows-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| MainTabViewApproxWidth | ``600`` |
| TabViewApproxWidth | ``FE`Evaluate[FEPrivate`If[FEPrivate`SameQ[FEPrivate`$OperatingSystem, "Windows"], 580, 660]]`` |
| HighlightColor | ``None`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Services`getServiceModelList["OpenAI", <|"Service" -> "OpenAI", "ServiceConnectionRequest" -> "Chat", "PreprocessingFunction" -> Identity, "SupportedParameters" -> {"FrequencyPenalty", "MaxTokens", "Messages", "Model", "PresencePenalty", "ProcessResultQ", "StopTokens", "Stream", "Temperature", "TotalProbabilityCutoff", HandlerFunctions, HandlerFunctionsKeys}, "ParameterMap" -> {}, "PostprocessingFunction" -> Identity, "ProcessResultQ" -> True, "ModelList" :> Enclose[ServiceExecu...
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$957916
|>
```

</details>

Screenshot:

![image](https://github.com/WolframResearch/Chatbook/assets/135765065/5e8c90a4-4c91-4f4c-8d10-6401f6b49727)

**Comment by rhennigan** [comment]
This is due to an ongoing service outage at OpenAI: https://status.openai.com/incidents/62wkltqhbrmk

To populate the popup menu that chooses the model name, we need to make an API call to OpenAI to get the model list. This API call failing is what led to that "Chatbook::Internal" failure you are seeing. I've merged a fix that avoids this by falling back to an input field when the model list is unavailable #597.

**Comment by oliverjandette** [comment]
Great, thank you!
