### ISSUE TITLE
Bad code from Chat

### ISSUE THREAD

**Issue by larrybloxham** [WolframResearch/Chatbook#685]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.0 for Mac OS X x86 (64-bit) (December 12, 2023)"`` |
| KernelVersion | ``"14.0.0 for Mac OS X x86 (64-bit) (December 13, 2023)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.0.3913547000"`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Actions`AttachCodeButtons[Dynamic[FE`attached$$224], CellObject["75b4effd-ce9d-4c47-849d-957b170a2d8b", "af77602a-9e0a-4677-919e-e066664156cd"], "Graphics[\n {\n  (* Draw boundary lines *)\n  InfiniteLine[{{0, 0}, {1, 1}}], \n  InfiniteLine[{{0, 0}, {1, -1}}], \n  InfiniteLine[{{1, 1}, {2, 0}}], \n  InfiniteLine[{{1, -1}, {2, 0}}], \n\n  (* Add labels *)\n  Text[\"Singularity\", {1, 0}], \n  Text[\"r = 0\", {2, 0}, {-1, 0}], \n  Text[\"r = 2M\", {0.5, 0.5}, {-1, -1}], \n  Text[\...
  "Failure" -> Failure["ConfirmationFailed", <|"Information" :> "ParentCell", "MessageTemplate" -> "``[``] did not return True.", "MessageParameters" :> {Wolfram`Chatbook`Actions`Private`chatCodeBlockQ, $Failed}, "ConfirmationType" -> "ConfirmBy", "Expression" :> $Failed, "Function" :> Wolfram`Chatbook`Actions`Private`chatCodeBlockQ|>]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$47666
|>
```

</details>

**Comment by raverydavis** [comment]
Do you still see this issue with the 1.4.5 release? You can update the paclet with `PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]`
