### ISSUE TITLE
The ServiceConnect of Claude-3 conflicts with the chat code

### ISSUE THREAD

**Issue by Chaofan-Gong** [WolframResearch/Chatbook#703]
Dear developer,

I checked the source code and found that Claude in the serviceconnect file "Anthropic.m" still uses old version completion-api instead of latest message-api, which prevents us from interacting with Claude-3 correctly.

![image](https://github.com/WolframResearch/Chatbook/assets/122721025/d0c18d34-07e2-4c59-a198-629bf581e870)

![image](https://github.com/WolframResearch/Chatbook/assets/122721025/9fb5fd21-fa18-400d-b6cb-782a4a9e5e5c)

**Comment by rhennigan** [comment]
You need a more recent version of the Anthropic service connection, which comes with 14.1.
