### ISSUE TITLE
CellToChatMessage problem in Wolfram tutor

### ISSUE THREAD

**Issue by theodoregray** [WolframResearch/Chatbook#710]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.6"`` |
| ReleaseID | ``"35426ddc2420db5aece51b8af7f18c8c0c231589"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.1 for Mac OS X x86 (64-bit) (May 21, 2024)"`` |
| KernelVersion | ``"14.1.0 for Mac OS X x86 (64-bit) (May 21, 2024)"`` |
| SystemID | ``"MacOSX-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| PersonaFavorites | ``{"CodeAssistant", "CodeWriter", "PlainChat"}`` |
| ChatNotebookSettings | ``<\|"InheritanceTest" -> True, "PersonaFavorites" -> {"CodeAssistant", "CodeWriter", "PlainChat"}\|>`` |

## Stack Data
```
catchTop
allowedMultimodalRoles0
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Models`toModelName[Missing["KeyAbsent", "Model"]]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$37115
|>
```

</details>

**Comment by theodoregray** [comment]
I get this error if I call CellToChatMessage on a very simple cell, but only after I have done a chat evaluation in a tutor notebook. That seems to cause some state to get set where CellToChatMessage fails in the future. Re-loading the ChatNotebook paclet resets things and it works again.

**Comment by rhennigan** [comment]
I created a ticket with more info here: #711
