### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by MarcoGordo** [WolframResearch/Chatbook#728]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.0"`` |
| ReleaseID | ``"00db891fc2d1dd712145aa46464ded3b71633f75"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 13.3 para Linux x86 (64-bit) (July 24, 2023)"`` |
| KernelVersion | ``"13.3.1 for Linux x86 (64-bit) (July 24, 2023)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| MainTabViewApproxWidth | ``600`` |
| TabViewApproxWidth | ``FE`Evaluate[FEPrivate`If[FEPrivate`SameQ[FEPrivate`$OperatingSystem, "Windows"], 580, 660]]`` |
| HighlightColor | ``None`` |

## Stack Data
```
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Services`getServiceModelList["PaLM", <|"Service" -> "PaLM", "ServiceConnectionRequest" -> "Chat", "PreprocessingFunction" -> Identity, "SupportedParameters" -> {"Model", "Temperature", "TotalProbabilityCutoff", "TopProbabilities"}, "ParameterMap" -> {}, "PostprocessingFunction" -> Identity, "ProcessResultQ" -> True, "ModelList" :> Enclose[ServiceExecute[Confirm[Wolfram`LLMFunctions`APIs`Common`ConnectToService["PaLM"]], "ChatModelList"]], "Icon" -> RawBoxes[TemplateBox[{}, "Serv...
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$83988
|>
```

</details>

**Comment by MarcoGordo** [comment]
Issue

**Comment by rhennigan** [comment]
This should be fixed in more recent versions of the Chatbook paclet. Evaluate the following to get the latest version:
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
```
