### ISSUE TITLE
Suggestion: Allow specifying the scope for all chat preferences in the "Notebooks" tab of the preferences UI

### ISSUE THREAD

**Issue by yuriever** [WolframResearch/Chatbook#774]
Thanks for this nice paclet.
I want to set the option "include chat history" in the preference panel true/false for different individual notebooks. Is there some `Options` to achieve this?

**Comment by rhennigan** [comment]
I've tagged this issue as a suggestion to add global/notebook/cell scoping to the preferences UI, but in the meantime, here are some ways you can do this programmatically.

You can specify this option at the notebook level using the following:
```
CreateNotebook[ "Chat", "IncludeHistory" -> False ]
```

Alternatively, you can modify the setting for an existing `NotebookObject[...]` or `CellObject[...]` using `CurrentChatSettings`. For example:
```
Wolfram`Chatbook`CurrentChatSettings[ InputNotebook[ ], "IncludeHistory" ] = False
```

**Comment by yuriever** [comment]
> I've tagged this issue as a suggestion to add global/notebook/cell scoping to the preferences UI, but in the meantime, here are some ways you can do this programmatically.
> 
> You can specify this option at the notebook level using the following:
> 
> ```
> CreateNotebook[ "Chat", "IncludeHistory" -> False ]
> ```
> 
> Alternatively, you can modify the setting for an existing `NotebookObject[...]` or `CellObject[...]` using `CurrentChatSettings`. For example:
> 
> ```
> Wolfram`Chatbook`CurrentChatSettings[ InputNotebook[ ], "IncludeHistory" ] = False
> ```

Thanks! That's exactly what I need.
