### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by achaseturner** [WolframResearch/Chatbook#829]
Crashed after I refined my question.

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.5.0"`` |
| ReleaseID | ``"f6143fb833bd66de9b3d322fa4de64b6787871ca"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.1 for Mac OS X ARM (64-bit) (July 16, 2024)"`` |
| KernelVersion | ``"14.1.0 for Mac OS X ARM (64-bit) (July 16, 2024)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| ServiceDefaultModel | ``<\|"GoogleGemini" -> Automatic, "OpenAI" -> "gpt-4o-2024-08-06"\|>`` |
| InheritanceTest | ``True`` |
| Model | ``<\|"Service" -> "OpenAI", "Name" -> "gpt-4o-2024-08-06"\|>`` |
| StyleSheetVersion | ``"1.5.0.3931772186"`` |

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Common`rootEvaluationCell[CellObject["63757986-1dab-4ae1-928f-faf19fa94c1b", "04d7b3bd-033f-4c65-9735-3ba024f6cb15"], {CellObject["01818950-ea19-4343-99df-73b72e4eb05c", "737147bf-773c-482b-8081-2453b0e58817"], CellObject["2503eff2-df42-47dc-a5a0-94cb5e98ec9a", "575d1cc1-9a3d-4170-b565-d323b9e7e588"]}]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$764173
|>
```

## Stack Data
```
insertInlineReference
loadDefinitionNotebook
ensureChatInputCell
throwFailure
trimURL
```

</details>

**Comment by achaseturner** [comment]
.nb files are not supported?!
[2024-10-10 Chatbook Crash.nb.omg.txt](https://github.com/user-attachments/files/17334420/2024-10-10.Chatbook.Crash.nb.omg.txt)
[SystemInformation.nb.omg.txt](https://github.com/user-attachments/files/17334421/SystemInformation.nb.omg.txt)

**Comment by rhennigan** [comment]
This appears to be the same underlying issue as #566
