### ISSUE TITLE
Insert Title Here

### ISSUE THREAD

**Issue by jrrk2** [WolframResearch/Chatbook#975]
Describe the issue in detail here. Attach any relevant screenshots or files. The section below was automatically generated. Remove any information that you do not wish to include in the report.

Opened a Chat assisted window and pasted some code. Crash occurred after several minutes thinking

https://github.com/WolframResearch/Chatbook/blob/4928c541e43282355f25275b5622b3a4fb1ae48e/Source/Chatbook/PromptGenerators/RelatedDocumentation.wl#L545-L552

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"2.0.0"`` |
| ReleaseID | ``"4928c541e43282355f25275b5622b3a4fb1ae48e"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.1 for Mac OS X ARM (64-bit) (July 16, 2024)"`` |
| KernelVersion | ``"14.1.0 for Mac OS X ARM (64-bit) (July 16, 2024)"`` |
| SystemID | ``"MacOSX-ARM64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``False`` |
| SynchronousEvaluation | ``False`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| InheritanceTest | ``True`` |
| Model | ``<\|"Service" -> "OpenAI", "Name" -> "gpt-4o-mini"\|>`` |
| StyleSheetVersion | ``"1.5.0.3931772186"`` |

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`PromptGenerators`RelatedDocumentation`Private`fetchDocumentationSnippets[{"https://resources.wolframcloud.com/FunctionRepository/resources/SetComplementMap", "https://resources.wolframcloud.com/FunctionRepository/resources/StringTemplateInput", "https://resources.wolframcloud.com/FunctionRepository/resources/TurtleArt", "paclet:ref/Toggler"}],
  "Information" -> "Text@@Source/Chatbook/PromptGenerators/RelatedDocumentation.wl:545,16-552,10",
  "ConfirmationType" -> "ConfirmBy",
  "Expression" :> StringTemplate[$Failed][4],
  "Function" -> StringQ,
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$135014,
  "Failure" -> Failure["ConfirmationFailed", <|"MessageTemplate" -> "Text@@Source/Chatbook/PromptGenerators/RelatedDocumentation.wl:545,16-552,10", "MessageParameters" -> {}, "ConfirmationType" -> "ConfirmBy", "Expression" :> StringTemplate[$Failed][4], "Information" -> "Text@@Source/Chatbook/PromptGenerators/RelatedDocumentation.wl:545,16-552,10", "Function" -> StringQ|>],
  "Arguments" -> {}
|>
```

## Stack Data
```
trimURL
throwFailure
catchTop
formatGeneratedPrompt
catchTopAs
withChatState
```

</details>

**Comment by rhennigan** [comment]
Can you try evaluating the following to see if it gives a string?
```
FrontEndResource[ "ChatbookStrings", "ProgressTextDownloadingSnippets" ]
```

If it doesn't, try evaluating `PacletDataRebuilt[]` then restart the front end to see if that resolves the issue.

**Comment by jrrk2** [comment]
I quit and restarted the App and that solved the problem. Therefore I guess it would not help to try that idea now.

On 10 Dec 2024, at 16:01, Rick Hennigan ***@***.***> wrote:



Can you try evaluating the following to see if it gives a string?

FrontEndResource[ "ChatbookStrings", "ProgressTextDownloadingSnippets" ]


If it doesn't, try evaluating PacletDataRebuild[] then restart the front end to see if that resolves the issue.
