### ISSUE TITLE
failed to enable AI Chat features 

### ISSUE THREAD

**Issue by ninja-lab** [WolframResearch/Chatbook#976]
In Pop!OS I just tried to enable AI chat and it throws this error. 

![Screenshot from 2024-12-11 09-20-05](https://github.com/user-attachments/assets/0a160510-b995-4ec1-bdeb-2038c1f4fe65)

<details>
<summary>Debug Data</summary>

| Property | Value |
| --- | --- |
| Name | ``"Wolfram/Chatbook"`` |
| Version | ``"1.4.6"`` |
| ReleaseID | ``"$RELEASE_ID$"`` |
| EvaluationEnvironment | ``"Session"`` |
| FrontEndVersion | ``"Desktop: 14.1 for Linux x86 (64-bit) (July 16, 2024)"`` |
| KernelVersion | ``"14.1.0 for Linux x86 (64-bit) (July 16, 2024)"`` |
| SystemID | ``"Linux-x86-64"`` |
| Notebooks | ``True`` |
| DynamicEvaluation | ``True`` |
| SynchronousEvaluation | ``True`` |
| TaskEvaluation | ``False`` |

## Settings

| Property | Value |
| --- | --- |
| StyleSheetVersion | ``"1.4.6.3927375719"`` |

## Stack Data
```
AttachSubmenu
MakeMenu
getAvailableServiceNames
throwFailure
trimURL
```

## Failure Data

```
<|
  "Evaluation" :> Wolfram`Chatbook`Services`Private`getAvailableServices0[Missing["KeyAbsent", ChatSubmit]]
  "Arguments" -> {}
  "Stack" :> Wolfram`Chatbook`Common`Private`$stack$35321
|>
```

</details>

**Comment by raverydavis** [comment]
Please try updating the Chatbook paclet first and if you are still encountering issues let us know here.
```
PacletInstall["Wolfram/Chatbook", UpdatePacletSites -> True]
```
